import { useState, useEffect } from "react";
import { Clock, FileEdit, CheckCircle2 } from "lucide-react";
import { getAuditLogs, type AuditLog } from "../../services/api";

interface AuditEntry {
  timestamp: string;
  action: string;
  user: string;
  userId: string;
  version: string;
  status: string;
  details: string;
}

const FIGMA_AUDIT: AuditEntry[] = [
  { timestamp: "2026-02-17 10:15:42", action: "Report Approved",       user: "Jane Doe",          userId: "EMP-4782", version: "v2.1", status: "Approved",   details: "Final review completed and report approved for submission" },
  { timestamp: "2026-02-17 10:08:15", action: "Document Edited",        user: "Jane Doe",          userId: "EMP-4782", version: "v2.0", status: "Modified",   details: "Paragraph 3 modified to include additional transaction details" },
  { timestamp: "2026-02-17 09:45:23", action: "Compliance Review",      user: "Michael Smith",     userId: "EMP-3421", version: "v1.5", status: "Reviewed",   details: "Regulatory citations verified against current requirements" },
  { timestamp: "2026-02-17 09:23:45", action: "Report Generated",       user: "AI System",         userId: "SYS-AUTO", version: "v1.0", status: "Generated",  details: "Initial SAR narrative generated by AI model v2.4.1" },
  { timestamp: "2026-02-17 09:22:18", action: "Risk Score Calculated",  user: "ML Engine",         userId: "SYS-ML",   version: "—",    status: "Calculated", details: "Risk score: 94/100 (High Risk Classification)" },
  { timestamp: "2026-02-17 09:20:05", action: "Case Assigned",          user: "System Supervisor", userId: "EMP-1001", version: "—",    status: "Assigned",   details: "Case assigned to Jane Doe for investigation" },
  { timestamp: "2026-02-16 16:15:30", action: "Enhanced Due Diligence", user: "John Smith",        userId: "EMP-2156", version: "—",    status: "Completed",  details: "EDD completed for Customer_A with additional documentation" },
  { timestamp: "2026-02-14 23:47:12", action: "Transaction Flagged",    user: "Monitoring System", userId: "SYS-MON",  version: "—",    status: "Flagged",    details: "Suspicious pattern detected: Structured deposits across multiple branches" },
];

export function AuditScreen() {
  const [auditHistory, setAuditHistory] = useState<AuditEntry[]>(FIGMA_AUDIT);

  useEffect(() => {
    getAuditLogs()
      .then((logs: AuditLog[]) => {
        if (!logs || logs.length === 0) {
          setAuditHistory(FIGMA_AUDIT);
          return;
        }
        const liveRows: AuditEntry[] = logs.map((log) => ({
          timestamp: log.created_at?.substring(0, 19).replace("T", " ") ?? "—",
          action: log.action ?? "Unknown",
          user: log.user_id ?? "System",
          userId: log.user_id ?? "SYS",
          version: "—",
          status: _actionToStatus(log.action),
          details: log.entity_type
            ? `${log.entity_type} ${log.entity_id} — ${JSON.stringify(log.details ?? {})}`
            : JSON.stringify(log.details ?? {}),
        }));
        setAuditHistory(liveRows.length > 0 ? liveRows : FIGMA_AUDIT);
      })
      .catch(() => setAuditHistory(FIGMA_AUDIT));
  }, []);

  function _actionToStatus(action: string): string {
    if (action === "APPROVE") return "Approved";
    if (action === "SAVE_DRAFT") return "Modified";
    if (action === "BLOCKCHAIN_ANCHOR") return "Completed";
    if (action === "SAR_GENERATED") return "Generated";
    return "Calculated";
  }

  const getStatusColor = (status: string) => {
    if (status === "Approved") return "#10B981";
    if (status === "Reviewed" || status === "Completed") return "#1F4ED8";
    if (status === "Modified" || status === "Flagged") return "#F59E0B";
    return "#9CA3AF";
  };

  const getStatusIcon = (status: string) => {
    if (status === "Approved" || status === "Completed") return CheckCircle2;
    if (status === "Modified" || status === "Flagged") return FileEdit;
    return Clock;
  };

  return (
    <div className="p-6">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-white mb-1" style={{ fontSize: '22px', fontWeight: 500 }}>
          Audit Trail
        </h1>
        <p className="text-[#9CA3AF]" style={{ fontSize: '13px' }}>
          Complete audit history for case SAR-2026-00421 • Customer_A
        </p>
      </div>

      {/* Audit Table */}
      <div className="border" style={{
        backgroundColor: '#102A43',
        borderColor: '#1F3A5F',
        borderRadius: '2px'
      }}>
        <div className="px-4 py-3 border-b" style={{ borderColor: '#1F3A5F' }}>
          <div className="flex items-center justify-between">
            <h2 className="text-white" style={{ fontSize: '16px', fontWeight: 500 }}>Audit History</h2>
            <div className="text-[#9CA3AF]" style={{ fontSize: '12px' }}>{auditHistory.length} events recorded</div>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b" style={{ borderColor: '#1F3A5F' }}>
                <th className="px-4 py-3 text-left text-[#9CA3AF]" style={{ fontSize: '12px', fontWeight: 500 }}>Timestamp</th>
                <th className="px-4 py-3 text-left text-[#9CA3AF]" style={{ fontSize: '12px', fontWeight: 500 }}>Action</th>
                <th className="px-4 py-3 text-left text-[#9CA3AF]" style={{ fontSize: '12px', fontWeight: 500 }}>User</th>
                <th className="px-4 py-3 text-left text-[#9CA3AF]" style={{ fontSize: '12px', fontWeight: 500 }}>User ID</th>
                <th className="px-4 py-3 text-left text-[#9CA3AF]" style={{ fontSize: '12px', fontWeight: 500 }}>Version</th>
                <th className="px-4 py-3 text-left text-[#9CA3AF]" style={{ fontSize: '12px', fontWeight: 500 }}>Status</th>
                <th className="px-4 py-3 text-left text-[#9CA3AF]" style={{ fontSize: '12px', fontWeight: 500 }}>Details</th>
              </tr>
            </thead>
            <tbody>
              {auditHistory.map((entry, index) => {
                const StatusIcon = getStatusIcon(entry.status);
                return (
                  <tr
                    key={index}
                    className="border-b hover:bg-[#0B1F3A] transition-colors"
                    style={{ borderColor: '#1F3A5F' }}
                  >
                    <td className="px-4 py-3 text-[#E5E7EB]" style={{ fontSize: '12px' }}>{entry.timestamp}</td>
                    <td className="px-4 py-3 text-white" style={{ fontSize: '13px', fontWeight: 500 }}>{entry.action}</td>
                    <td className="px-4 py-3 text-[#E5E7EB]" style={{ fontSize: '13px' }}>{entry.user}</td>
                    <td className="px-4 py-3 text-[#9CA3AF]" style={{ fontSize: '12px' }}>{entry.userId}</td>
                    <td className="px-4 py-3 text-[#9CA3AF]" style={{ fontSize: '12px' }}>{entry.version}</td>
                    <td className="px-4 py-3" style={{ fontSize: '12px' }}>
                      <div className="flex items-center gap-2">
                        <StatusIcon className="w-3.5 h-3.5" style={{ color: getStatusColor(entry.status) }} strokeWidth={1.5} />
                        <span style={{ color: getStatusColor(entry.status) }}>{entry.status}</span>
                      </div>
                    </td>
                    <td className="px-4 py-3 text-[#9CA3AF]" style={{ fontSize: '12px' }}>{entry.details}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Timeline View */}
      <div className="grid grid-cols-2 gap-4 mt-4">
        <div className="border p-4" style={{
          backgroundColor: '#102A43',
          borderColor: '#1F3A5F',
          borderRadius: '2px'
        }}>
          <div className="text-white mb-4" style={{ fontSize: '14px', fontWeight: 500 }}>Timeline Visualization</div>
          <div className="space-y-4">
            {auditHistory.slice(0, 5).map((entry, index) => {
              const StatusIcon = getStatusIcon(entry.status);
              return (
                <div key={index} className="relative pl-6">
                  <div
                    className="absolute left-0 top-1.5 w-3 h-3 flex items-center justify-center"
                    style={{ backgroundColor: getStatusColor(entry.status), borderRadius: '1px' }}
                  >
                    <StatusIcon className="w-2 h-2 text-white" strokeWidth={2} />
                  </div>
                  <div className="text-white mb-0.5" style={{ fontSize: '12px', fontWeight: 500 }}>{entry.action}</div>
                  <div className="text-[#9CA3AF]" style={{ fontSize: '11px' }}>{entry.user} • {entry.timestamp}</div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="border p-4" style={{
          backgroundColor: '#102A43',
          borderColor: '#1F3A5F',
          borderRadius: '2px'
        }}>
          <div className="text-white mb-4" style={{ fontSize: '14px', fontWeight: 500 }}>Audit Statistics</div>
          <div className="space-y-3">
            {[
              ["Total Actions",  String(auditHistory.length)],
              ["System Actions", String(auditHistory.filter((e) => e.userId.startsWith("SYS")).length)],
              ["User Actions",   String(auditHistory.filter((e) => !e.userId.startsWith("SYS")).length)],
              ["Modifications",  String(auditHistory.filter((e) => e.status === "Modified").length)],
              ["Approvals",      String(auditHistory.filter((e) => e.status === "Approved").length)],
              ["Version Count",  auditHistory.find((e) => e.version !== "—")?.version ?? "v1.0"],
            ].map(([label, value]) => (
              <div key={label} className="flex items-center justify-between pb-2 border-b" style={{ borderColor: '#1F3A5F' }}>
                <span className="text-[#9CA3AF]" style={{ fontSize: '12px' }}>{label}</span>
                <span className="text-white" style={{ fontSize: '13px', fontWeight: 500 }}>{value}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
